version: '3.3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src/app.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - mongo
    working_dir: /app
    command: flask run --host=0.0.0.0

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
