###
POST http://127.0.0.1:5000/movie HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNDI1NDU3NSwianRpIjoiMzNlYjg1MTUtZGQ2NC00MmZjLWIzMTktNDAwZDYyYzIyZWI0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY2YzU2NzBlNjZjMGIwNDRlZjViM2Q3MyIsIm5iZiI6MTcyNDI1NDU3NSwiY3NyZiI6ImIwOTczM2M2LWI0MTctNGQ0Yy1iM2FmLTQ4MmRiZWI5Yzg0YiIsImV4cCI6MTcyNDI1NTQ3NX0.OdeUwmw2Qgb8hwJQWaSTnM3C0mk9m2XpGMiHL_LoWE4

{
    "name": "Normal People",
    "actors": "Daisy Edgar-Jones, Glen Powell",
    "director": "Lee Isaac Chung",
    "genre": "Action, Adventure",
    "rating": "8",
    "realeseDate": "2024-07-19"
}

### 
GET http://127.0.0.1:5000/movie HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNDI1NTQ4NywianRpIjoiNTIxMWM3NjQtMDkzMy00YTRkLWJjMDctZmExY2YyZjEwZTQ3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY2YzU2NzBlNjZjMGIwNDRlZjViM2Q3MyIsIm5iZiI6MTcyNDI1NTQ4NywiY3NyZiI6IjMxYmMwMjQ5LWU1ZTMtNDZlZC05ZmVjLTFhMzU3Y2QwNTlkZiIsImV4cCI6MTcyNDI1NjM4N30.-d7y6A2RDf8piLzncFm6UnZxmwxSusWdNlpU86xO0xo

### 
GET http://127.0.0.1:5000/movie/66c60ce0c631af67b153fab7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNDI1NTQ4NywianRpIjoiNTIxMWM3NjQtMDkzMy00YTRkLWJjMDctZmExY2YyZjEwZTQ3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY2YzU2NzBlNjZjMGIwNDRlZjViM2Q3MyIsIm5iZiI6MTcyNDI1NTQ4NywiY3NyZiI6IjMxYmMwMjQ5LWU1ZTMtNDZlZC05ZmVjLTFhMzU3Y2QwNTlkZiIsImV4cCI6MTcyNDI1NjM4N30.-d7y6A2RDf8piLzncFm6UnZxmwxSusWdNlpU86xO0xo

###
PUT http://127.0.0.1:5000/movie/66c60ce0c631af67b153fab7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNDI1NTQ4NywianRpIjoiNTIxMWM3NjQtMDkzMy00YTRkLWJjMDctZmExY2YyZjEwZTQ3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY2YzU2NzBlNjZjMGIwNDRlZjViM2Q3MyIsIm5iZiI6MTcyNDI1NTQ4NywiY3NyZiI6IjMxYmMwMjQ5LWU1ZTMtNDZlZC05ZmVjLTFhMzU3Y2QwNTlkZiIsImV4cCI6MTcyNDI1NjM4N30.-d7y6A2RDf8piLzncFm6UnZxmwxSusWdNlpU86xO0xo

{
    "name": "Normal People",
    "done": true
}

### 
DELETE http://127.0.0.1:5000/movie/66c562e732058cd095f4c353 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNDI1NDU3NSwianRpIjoiMzNlYjg1MTUtZGQ2NC00MmZjLWIzMTktNDAwZDYyYzIyZWI0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY2YzU2NzBlNjZjMGIwNDRlZjViM2Q3MyIsIm5iZiI6MTcyNDI1NDU3NSwiY3NyZiI6ImIwOTczM2M2LWI0MTctNGQ0Yy1iM2FmLTQ4MmRiZWI5Yzg0YiIsImV4cCI6MTcyNDI1NTQ3NX0.OdeUwmw2Qgb8hwJQWaSTnM3C0mk9m2XpGMiHL_LoWE4

###
POST http://127.0.0.1:5000/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "DenilsonPerezC",
    "password": "Waataakaa18."
}

###
POST http://127.0.0.1:5000/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "DenilsonPerezC",
    "password": "Waataakaa18."
}


//Docker 
###
POST http://localhost:5000/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "DenilsonPerezC",
    "password": "Waataakaa18."
}

###
POST http://localhost:5000/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "DenilsonPerezC",
    "password": "Waataakaa18."
}

### 
GET http://localhost:5000/movie HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNDI2NTM0NiwianRpIjoiZGJkMDQ2YzYtMGI2ZS00YTVhLThjOWYtYmU1NTNmYWMxZDNjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY2YzYzMzdiZWVkMzZjNzcyMjJhZjI0ZCIsIm5iZiI6MTcyNDI2NTM0NiwiZXhwIjoxNzI0MjY2MjQ2fQ.kcdsCIv24_7_oTSGGdcgIPqm2QQTXslUgdUXgXkwv2s

### 
GET http://localhost:5000/movie/66c60de15b7c783b8c0a843f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNDI2NTM0NiwianRpIjoiZGJkMDQ2YzYtMGI2ZS00YTVhLThjOWYtYmU1NTNmYWMxZDNjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY2YzYzMzdiZWVkMzZjNzcyMjJhZjI0ZCIsIm5iZiI6MTcyNDI2NTM0NiwiZXhwIjoxNzI0MjY2MjQ2fQ.kcdsCIv24_7_oTSGGdcgIPqm2QQTXslUgdUXgXkwv2s

###
PUT http://localhost:5000/movie/66c60de15b7c783b8c0a843f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNDI2NTM0NiwianRpIjoiZGJkMDQ2YzYtMGI2ZS00YTVhLThjOWYtYmU1NTNmYWMxZDNjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY2YzYzMzdiZWVkMzZjNzcyMjJhZjI0ZCIsIm5iZiI6MTcyNDI2NTM0NiwiZXhwIjoxNzI0MjY2MjQ2fQ.kcdsCIv24_7_oTSGGdcgIPqm2QQTXslUgdUXgXkwv2s

{
    "name": "Normal People",
    "done": true
}

### 
DELETE http://localhost:5000/movie/66c60de15b7c783b8c0a843f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNDI2NTM0NiwianRpIjoiZGJkMDQ2YzYtMGI2ZS00YTVhLThjOWYtYmU1NTNmYWMxZDNjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY2YzYzMzdiZWVkMzZjNzcyMjJhZjI0ZCIsIm5iZiI6MTcyNDI2NTM0NiwiZXhwIjoxNzI0MjY2MjQ2fQ.kcdsCIv24_7_oTSGGdcgIPqm2QQTXslUgdUXgXkwv2s