###
POST http://127.0.0.1:5000/movie HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNDE5NzI5MSwianRpIjoiOTBjMTE5MTctZGEzNy00MDczLTkzMjktMTc1M2I0MzRhNmE4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY2YzUyM2E1MDQzMTcyMmRjMzg4ODY2NCIsIm5iZiI6MTcyNDE5NzI5MSwiY3NyZiI6IjBiOWMyN2E0LWI3MTktNGQwNS04NGZjLWI5MTZmZTI3OTEyNyIsImV4cCI6MTcyNDE5ODE5MX0.ierXCSfVQJqfJzhpFpK5AgGWxDrS3UrHe7UG1q7r1F8

{
    "name": "Twisters",
    "actors": "Daisy Edgar-Jones, Glen Powell",
    "director": "Lee Isaac Chung",
    "genre": "Action, Adventure",
    "rating": "8",
    "realeseDate": "2024-07-19"
}

### 
GET http://127.0.0.1:5000/movie HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNDIwMjU4NiwianRpIjoiYjFkZTA5ZjMtN2E0Zi00ZWFmLWEyYTAtYzU1ZDVlNzAwZTFjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY2YzUyM2E1MDQzMTcyMmRjMzg4ODY2NCIsIm5iZiI6MTcyNDIwMjU4NiwiY3NyZiI6IjQyNzM5NTkxLTg2MjktNGQ1ZS05NWYzLWEwMTkzMmRiZDAwZSIsImV4cCI6MTcyNDIwMzQ4Nn0.jBiqOX7pGGfZJdEtPHxluC5PUBF324pqd5qp0R9Nx78

### 
GET http://127.0.0.1:5000/movie/66c4e87a3852c5278627a0ab HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNDE3OTkyMywianRpIjoiYjIyNWJmNTEtMWI3OC00YmI1LWI4YmMtYTcyNmFjYzdjNTFhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY2YzQyNWI1NWI0MzExNzc2MjU2NWI4MiIsIm5iZiI6MTcyNDE3OTkyMywiY3NyZiI6ImJiNjkwMjhiLTYyMWUtNGRlZS1hNDkyLWNiMTIyZTNjNTgzZiIsImV4cCI6MTcyNDE4MDgyM30.GqYH36h27iXe1OKhyWwIvMteVukuT4s99G6-5cbaiN8

###
PUT http://127.0.0.1:5000/movie/66c529e4a4774ab103d9a471 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNDIxMDEzNiwianRpIjoiOTI1ZDdiODktMjc0ZS00OTY1LWIwMWItMDIxOTdlZGY0MzI1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY2YzUyM2E1MDQzMTcyMmRjMzg4ODY2NCIsIm5iZiI6MTcyNDIxMDEzNiwiY3NyZiI6IjBmZTJiYmRlLWFlNzUtNDdlMi05MDEwLWZiYTEyM2U1YjVlYyIsImV4cCI6MTcyNDIxMTAzNn0.Icpffi2taHNiKyL4v3q-E7D2Jrex-dtKa4etgVdd04c

{
    "name": "Normal Peoples",
    "done": true
}

### 
DELETE http://127.0.0.1:5000/movie/66c4e87a3852c5278627a0ab HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNDE3OTkyMywianRpIjoiYjIyNWJmNTEtMWI3OC00YmI1LWI4YmMtYTcyNmFjYzdjNTFhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY2YzQyNWI1NWI0MzExNzc2MjU2NWI4MiIsIm5iZiI6MTcyNDE3OTkyMywiY3NyZiI6ImJiNjkwMjhiLTYyMWUtNGRlZS1hNDkyLWNiMTIyZTNjNTgzZiIsImV4cCI6MTcyNDE4MDgyM30.GqYH36h27iXe1OKhyWwIvMteVukuT4s99G6-5cbaiN8

###
POST http://127.0.0.1:5000/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "DenilsonPerezC",
    "password": "Waataakaa18."
}

###
POST http://127.0.0.1:5000/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "DenilsonPerezC",
    "password": "Waataakaa18."
}